spring.application.name=Bank-Management-System2


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Bank_Management_System2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atm1*}

server.port=${PORT:8081}