spring.application.name=Bank-Management-System2

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bank_management_system2}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:atm1*}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port = 8080


# This tells Spring: "Look for a variable named SPRING_DATASOURCE_URL.
# If you don't find it, use the local localhost URL as a backup."
